### PR TITLE
to close #11

### LINKED ISSUE #11: ios9 Orientation problem
ios9 orientation problem is still here!.
Tested with ios 9.2.

version used: last stable, and last developer and master

### PR DESCRIPTION
**Pull request by gimox**
fix problem on ios9 orientation

### CODE REVIEW

**Comment by odrobnik** [comment]
Anybody able to confirm that this is working? Especially on iOS 7 and iOS 9?

**Comment by odrobnik** [comment]
@gimox Would you mind adapting your fix such that it does not break functionality in earlier iOS versions?

**Comment by FreeKent** [comment]
@odrobnik @nickob , please look at this pull request #14, it fixes the problem

**Comment by odrobnik** [comment]
PR #14 was better as it deals with higher system versions better.

**Pull request closed without merging**
