### PR TITLE
Fix crash due to invalid view frames on iOS 9, fixes #7

### LINKED ISSUE #7: iOS 9 crash when loupe is shown
On iOS 9, whenever the loupe tries to appear, the app crashes during renderInContext(DTLoupeView.m line 584 due to views in hierarchy having (inf,inf) positions.

### PR DESCRIPTION
**Pull request by amro**
Again, we should fix the root issue in DTRichTextEditor but this is a good failsafe.

### CODE REVIEW

**Comment by odrobnik** [comment]
@amro is this change still required or was it superseded by the selection rectangles fix?

**Comment by amro** [comment]
I think the selection rectangles fix is sufficient. @Daij-Djan said this fix actually would not work on its own, so I suggest we remove it. In fact, if his fix prevents the crash on iOS 8 then we should remove -hideInvalidLayersInView: all together, in my opinion.

**Comment by amro** [comment]
That said, it will not hurt if you want it as a precaution. If others make the same mistake and this catches it, then great. But we're really hiding the mistake.

**Comment by odrobnik** [comment]
Let's try without... would you mind putting together a PR to remove the unnecessary parts?

**Comment by amro** [comment]
Yes. To be clear, you want a PR to remove -hideInvalidLayersInView:, correct?

**Comment by odrobnik** [comment]
Yes, I worry that the constant messing with the layers might be bad for performance anyway.. Somebody needs to try it on iOS 8 with the new fix though… but I have a feeling that it would probably work.

**Comment by amro** [comment]
I can attempt to remove the first commit - I'm not sure whether github will play nice with that or not.

**Comment by odrobnik** [comment]
Thank you @amro for your great efforts! Always sad to see so much code be leaving the project ... ;-)

**Pull request merged**
