### PR TITLE
Update image assets for iOS 9

### PR DESCRIPTION
**Pull request by artonragsdale**

### CODE REVIEW

**Comment by odrobnik** [comment]
Do you also have @3x assets? Those would also be missing

**Comment by odrobnik** [comment]
@artonragsdale respond please. We need 3x assets as well

**Comment by artonragsdale** [comment]
I could only find 3x assets for a subset of the images.

**Comment by odrobnik** [comment]
What do you mean "find"? The current pull request has none

**Comment by artonragsdale** [comment]
I used the artwork extractor you suggested in a blog post, but only found a few @3x images.  I'll open a new pull request with them.

**Pull request closed without merging**
