### PR TITLE
Use drawViewHierarchyInRect to render frame if available

### PR DESCRIPTION
**Pull request by artonragsdale**
Fixes issues with renderInContext on iOS 7+

### CODE REVIEW

**Comment by odrobnik** [comment]
Why are you trying to undo this crash fix?

**Comment by artonragsdale** [comment]
Because it wasn't actually a crash fix. More of a crash deferral. In iOS 9 it no longer worked. The correct way to handle it is to use the new iOS 7 method for capturing a view if available. Then hiding invalid views is no longer necessary.

**Comment by odrobnik** [comment]
But what about the situation where the new layer draing method would produce blank output from tiled layers?

**Comment by artonragsdale** [comment]
How can I test this situation?

**Comment by odrobnik** [comment]
Have a Long enough attributed string so that it causes use of a CATiledLayer... AFAIK this was broken in several iOS versions before iOS 9

**Comment by artonragsdale** [comment]
There are definitely some issues with this approach.  Everything renders
perfectly in simulator but on device text glyphs do not appear in the
loupe. Everything else, such as insertion blinker and custom views appear
properly though.  Unfortunately there is still a crash whenever the loupe
appears in iOS 9.  I'll close this pull request and create an issue for the
crash if one does not already exist.

**Pull request closed without merging**
